name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Install markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2

      - name: Build MkDocs site
        run: mkdocs build

      - name: Remove symlinks and hard links
        run: |
          find site -type l -exec rm -f {} \;

      - name: Ensure size limit
        run: |
          TOTAL_SIZE=$(du -sh site | cut -f1)




