name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          mkdocs build

      - name: Check if site directory exists
        run: |
          if [ -d "./site" ]; then echo "Directory exists"; else echo "Directory does not exist"; fi

      - name: List site directory before upload
        run: ls -la ./site || echo "Site directory not found"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-site
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mkdocs-site
          path: ./site

      - name: List site directory after download
        run: ls -la ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


